### PR TITLE
Support for Julia files

### PR DESCRIPTION
**Pull request by nobelt**

### CODE REVIEW

**Comment by pgilad** [comment]
Hey, thank you 👏  can you please fix the failing tests?

**Comment by pgilad** [comment]
Hey it looks like there is something wrong with consecutive comments, nice catch! I'll take a look at it and update soon 🙏

**Comment by pgilad** [comment]
Closed and merged by #122 
Thank you so much for your contribution and the critical bug (of multi-line) discovery 🏆

**Comment by nobelt** [comment]
No problem, thank you so much for resolving!

**Pull request closed without merging**
