### PR TITLE
Add support for Crystal

### PR DESCRIPTION
**Pull request by MakeNowJust**
I want to use `leasot` for [Crystal](https://crystal-lang.org) development because `leasot` is great tool. Thank you!

### CODE REVIEW

**Comment by MakeNowJust** [comment]
Wow! Thank you for extreme quick response!

**Comment by MakeNowJust** [comment]
Ah, I missed updating `README.md`'s table. Should I do it?

**Comment by pgilad** [comment]
No problem, thanks for the PR!

**Comment by pgilad** [comment]
@MakeNowJust Already did ;-)

**Pull request merged**
