### PR TITLE
Issue 85

### PR DESCRIPTION
**Pull request by SeanSobey**
This includes changes in [issue-45](https://github.com/pgilad/leasot/pull/87) and [issue-67](https://github.com/pgilad/leasot/pull/88)

### CODE REVIEW

**Comment by SeanSobey** [comment]
See [issue 85](https://github.com/pgilad/leasot/issues/85)

**Comment by pgilad** [comment]
I would add only this fix (https://github.com/pgilad/leasot/pull/89/commits/f820c19e8cfb3d589db01f526285e120ba0145e8) to this PR, perhaps also with the UT fix

**Comment by SeanSobey** [comment]
Yeah sorry the pull requests and history got a little messy, but I needed the fixed from the other 2 PR to be able to test on my windows machine. Once PR 87 and 88 go in then this will only contain the commits related to the feature ( [f820c19](https://github.com/pgilad/leasot/pull/89/commits/f820c19e8cfb3d589db01f526285e120ba0145e8) and [808fd8bad](808fd8bad7166190a9bad53ba945eac287989d7e))

**Comment by pgilad** [comment]
Thanks a lot @SeanSobey I manually merged this code - see https://github.com/pgilad/leasot/commit/cb765bc2cae89c7afb064438cf12558e243a1745

**Pull request closed without merging**
