### PR TITLE
Fixed parsing of trailing references to allow slashes in comments

### PR DESCRIPTION
**Pull request by sompylasar**
Fixes https://github.com/pgilad/leasot/issues/58

### CODE REVIEW

**Comment by pgilad** [comment]
Wow looks great! Awesome idea about separating that tough regex with comments... I'll review it later before merging

**Comment by sompylasar** [comment]
@pgilad Thanks! I've added a couple tests for that, and ensured that the trailing references get parsed as well (there was a test for that), now they require a mandatory space before the slash.

**Comment by sompylasar** [comment]
@pgilad Just curious, I have never seen such a syntax with trailing references. Is this a Ruby community feature, or your team preference?

**Comment by pgilad** [comment]
I think it was added as a PR by someone who's team apparently uses it, I've never used that syntax myself

**Comment by pgilad** [comment]
🏆  Awesome work man!

**Pull request merged**
