### PR TITLE
Added support for python

### PR DESCRIPTION
**Pull request by swmcc**
Both for # and """ multi line commits. Great utility :)

### CODE REVIEW

**Comment by Pharb** [comment]
Gread addition :+1:
Your test integration (parser-spec.js) seems to be incomplete.

**Comment by pgilad** [comment]
Hey @swmcc thanks for the PR! It seems to me like you duplicated the test for the ruby parsing (probably some commits got mixed up?)
Can you fix the test and rebase the commit?

**Comment by swmcc** [comment]
Yeah I've done something stupid. I will rectify later on today, sorry about that. I'll rebase and commit.

**Comment by pgilad** [comment]
Sure no problems... We all lead a double life in real work ;)

**Pull request closed without merging**
